<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net35</TargetFramework>
        <DefineConstants>MONO</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
      <Reference Include="netstandard" IncludeAssets="compile">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Graveyard Keeper 2\GraveyardKeeper2_Data\Managed\netstandard.dll</HintPath>
      </Reference>
	  <Reference Include="System.Runtime">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Graveyard Keeper 2\GraveyardKeeper2_Data\Managed\System.Runtime.dll</HintPath>
	  </Reference>
    </ItemGroup>
    <ItemGroup>
      <PackageReference Update="UnityEngine.Modules" Version="5.3.2" />
    </ItemGroup>
</Project>
